# _config.yml
title: "Yannis Ntekas"
description: "Spatial RNA-seq | Host-Microbiome | Non-coding RNA"
baseurl: "" # leave blank for user.github.io
url: "https://ntekasi.github.io" # replace with your GitHub URL

# === Optional for icon rendering ===
plugins:
  - jekyll-seo-tag